name: Update Azure VM passwords
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2

    - name: Log into Azure using github secret AZURE_CREDENTIALS
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Connect to KeyVault and retrieve all secrets
      uses: Azure/get-keyvault-secrets@v1
      id: myGetSecretAction
      with: 
        keyvault: "github-secrets-vault3"
        secrets: '*'

    #- name: Convert outputs from get-keyvault-secrets action and set as PowerShell environment variable
    #  run: |
    #    $env:Secrets = ConvertFrom-Json -InputObject '${{ toJson(steps.myGetSecretAction.outputs) }}'
    #    $env:Secrets
    #  shell: powershell

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          write-host "Creating PowerShell hashtable of all outputs from: [steps.myGetSecretAction]"
          $Secrets = (ConvertFrom-Json -InputObject '${{ toJson(steps.myGetSecretAction.outputs) }}' -AsHashtable)
          write-host "Looping through each key and updating the local username"
          Foreach ($key in $Secrets.keys) {
            If (Get-AzVm -Name $key -ErrorAction SilentlyContinue) {
              write-host "Server found: [$key]... Changing local admin password"
              $adminUser = (Get-AzVm -Name $key | Select-Object -ExpandProperty OSProfile).AdminUsername
              write-host "local admin: [$adminUser]"

              echo "VM_NAME_ENV=steps.myGetSecretAction.outputs.$test" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
              write-host "password is ${{ env.VM_NAME_ENV }}"
            }
            Else {
             write-warning "Server NOT found: [$key]."
            }            
          }
        azPSVersion: 'latest'