name: Update Azure VM passwords
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2

    - name: Log into Azure using github secret AZURE_CREDENTIALS
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Connect to KeyVault and retrieve all secrets
      uses: Azure/get-keyvault-secrets@v1
      id: myGetSecretAction
      with: 
        keyvault: "github-secrets-vault3"
        secrets: '*'

    #- name: Convert outputs from get-keyvault-secrets action and set as PowerShell environment variable
    #  run: |
    #    $env:Secrets = ConvertFrom-Json -InputObject '${{ toJson(steps.myGetSecretAction.outputs) }}'
    #    $env:Secrets
    #  shell: powershell

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $Secrets = (ConvertFrom-Json -InputObject '${{ toJson(steps.myGetSecretAction.outputs) }}' -AsHashtable)
          $Secrets
          $Secrets.keys
          $Secrets.values
          $test = $Secrets.keys[0]
          write-host "server is $test"
          write-host '::set-output name=SELECTED_VM::$test'
          ${{ steps.myGetSecretAction.outputs.SELECTED_VM }}
          write-host "password is ${{ steps.myGetSecretAction.outputs.SELECTED_VM }}"
          write-host "password is ${{ steps.myGetSecretAction.outputs.pwd9000vm02 }}"
        azPSVersion: 'latest'