name: Update Azure VM passwords
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: "github-secrets-vault3"
        secrets: '*'
      id: myGetSecretAction