name: Update Azure VM passwords
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2

    - name: Log into Azure using github secret AZURE_CREDENTIALS
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Connect to KeyVault and retrieve all secrets   
      uses: Azure/get-keyvault-secrets@v1
      id: myGetSecretAction
      with: 
        keyvault: "github-secrets-vault3"
        secrets: '*'

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          write-host "The previous action loads all our secrets into environment variables"
          write-host "We will exclude some default environment variables and only capture our secrets"
          #write-host ${{ join(steps.myGetSecretAction.outputs.*, '\n') }}
          write-host ${{ join(steps.myGetSecretAction.*, '\n') }}
        azPSVersion: 'latest'