name: Update Azure VM passwords
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2

    - name: Log into Azure using github secret AZURE_CREDENTIALS
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Connect to KeyVault and retrieve all secrets
      uses: Azure/get-keyvault-secrets@v1
      id: myGetSecretAction
      with: 
        keyvault: "github-secrets-vault3"
        secrets: '*'

    - name: Convert outputs from get-keyvault-secrets action to PowerShell object
      run: $env:Secrets = ConvertFrom-Json -InputObject '${{ toJson(steps.myGetSecretAction.outputs) }}'
      shell: powershell

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          write-host "here are our secrets set in previous"
          $env:Secrets      
        azPSVersion: 'latest'