name: Update Azure VM passwords
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2

    - name: Set Key Vault Variable
      run: |
        echo "KEY_VAULT_NAME=github-secrets-vault3" >> $GITHUB_ENV

    - name: Log into Azure using github secret AZURE_CREDENTIALS
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Connect to KeyVault and retrieve all secrets
      uses: Azure/get-keyvault-secrets@v1
      id: myGetSecretAction
      with: 
        keyvault: ${{ env.KEY_VAULT_NAME }}
        secrets: '*'

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $keyVaultName = ${{ env.KEY_VAULT_NAME }}
          write-host "Creating PowerShell hashtable of all outputs from: [$keyVaultName]"
          $Secrets = (ConvertFrom-Json -InputObject '${{ toJson(steps.myGetSecretAction.outputs) }}' -AsHashtable)
          write-host "Looping through each key and changing the local admin password"
          Foreach ($hash in $Secrets.GetEnumerator()) {
            If (Get-AzVm -Name $hash.Name -ErrorAction SilentlyContinue) {
              write-host "Server found: [$($hash.Name)]... Changing local admin password"
              $adminUser = (Get-AzVm -Name $hash.Name | Select-Object -ExpandProperty OSProfile).AdminUsername
              write-host "local admin: [$adminUser]"
              write-host "Password: [$($hash.Value)]"
            }
            Else {
             write-warning "Server NOT found: [$key]."
            }            
          }
        azPSVersion: 'latest'